baseURL: https://codingricky.github.io/polymorph_static/
languageCode: en-us
title: Polymorph Solutions
theme: hugo-fresh
publishDir: docs

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Innovative. Creative. Mobile.
    # Hero subtitle (optional)
    subtitle: Polymorph Solutions
    # Hero image (from /images/___)
    image: screenshots/iphonex.png
    # Footer logos (from /images/logos/clients/___.svg)
    
